-- Additive migration: New tables for metro resume sections
-- DO NOT drop existing tables (profile, documents remain untouched)

-- Disable RLS for existing tables (match current setup)
ALTER TABLE public.profile DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents DISABLE ROW LEVEL SECURITY;

-- Work Experience Table
CREATE TABLE IF NOT EXISTS public.work_experience (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role text NOT NULL,
    company text NOT NULL,
    start_date date NOT NULL,
    end_date date,
    is_current boolean DEFAULT false,
    description text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Skills Table
CREATE TABLE IF NOT EXISTS public.skills (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    level int NOT NULL CHECK (level BETWEEN 1 AND 5),
    category text NOT NULL CHECK (category IN ('Technical', 'Safety', 'Soft Skills')),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Certifications Table
CREATE TABLE IF NOT EXISTS public.certifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    issuer text NOT NULL,
    date_earned date NOT NULL,
    expiry_date date,
    certificate_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Achievements Table
CREATE TABLE IF NOT EXISTS public.achievements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    date date NOT NULL,
    icon text DEFAULT 'fa-trophy',
    category text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Education Table
CREATE TABLE IF NOT EXISTS public.education (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution text NOT NULL,
    degree text NOT NULL,
    field text,
    year int NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Disable RLS for all new tables (match existing setup)
ALTER TABLE public.work_experience DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.certifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.education DISABLE ROW LEVEL SECURITY;

-- Optional: Storage policy for certificate uploads (matches existing resume-assets bucket)
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" 
ON storage.objects 
FOR ALL 
TO public 
USING (bucket_id = 'resume-assets') 
WITH CHECK (bucket_id = 'resume-assets');
