-- Drop existing tables if they exist (to clear bad schema)
DROP TABLE IF EXISTS public.documents CASCADE;
DROP TABLE IF EXISTS public.profile CASCADE;

-- Create Profile Table
CREATE TABLE public.profile (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text,
    professional_title text,
    introduction text,
    about_me text,
    contact_info text,
    profile_photo_url text,
    banner_url text,
    stat_years text,
    stat_projects text,
    stat_success text,
    feature1_title text,
    feature1_desc text,
    feature2_title text,
    feature2_desc text,
    feature3_title text,
    feature3_desc text
);

-- Create Documents Table
CREATE TABLE public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    url text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Disable Row Level Security for both tables
ALTER TABLE public.profile DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents DISABLE ROW LEVEL SECURITY;

-- Storage Policy for resume-assets bucket
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" 
ON storage.objects 
FOR ALL 
TO public 
USING (bucket_id = 'resume-assets') 
WITH CHECK (bucket_id = 'resume-assets');
